CREATE TABLE IF NOT EXISTS aihub_casbin_rule (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  ptype VARCHAR(16) NOT NULL,
  v0 VARCHAR(255) DEFAULT NULL,
  v1 VARCHAR(255) DEFAULT NULL,
  v2 VARCHAR(255) DEFAULT NULL,
  v3 VARCHAR(255) DEFAULT NULL,
  v4 VARCHAR(255) DEFAULT NULL,
  v5 VARCHAR(255) DEFAULT NULL,
  rule_hash CHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_rule_hash (rule_hash),
  KEY idx_ptype (ptype),
  KEY idx_sub (v0),
  KEY idx_obj (v1),
  KEY idx_act (v2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
