CREATE TABLE IF NOT EXISTS aihub_tool_failure (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  failure_id VARCHAR(128) NOT NULL,
  app VARCHAR(64) NOT NULL DEFAULT 'aihub',
  namespace_id VARCHAR(128) NOT NULL,
  object VARCHAR(255) DEFAULT NULL,
  tool_id VARCHAR(128) NOT NULL,
  tool_version VARCHAR(64) DEFAULT NULL,
  agent_id VARCHAR(128) DEFAULT NULL,
  agent_version VARCHAR(64) DEFAULT NULL,
  runtime_id VARCHAR(128) DEFAULT NULL,
  session_id VARCHAR(128) DEFAULT NULL,
  run_id VARCHAR(128) DEFAULT NULL,
  trace_id VARCHAR(128) DEFAULT NULL,
  snapshot_id VARCHAR(128) DEFAULT NULL,
  attempt INT DEFAULT 0,
  error_code VARCHAR(128) DEFAULT NULL,
  error_message TEXT NOT NULL,
  retryable TINYINT(1) NOT NULL DEFAULT 0,
  input_digest VARCHAR(128) DEFAULT NULL,
  input_preview TEXT DEFAULT NULL,
  duration_millis BIGINT DEFAULT 0,
  metadata JSON DEFAULT NULL,
  reporter VARCHAR(128) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_tool_failure_id(failure_id),
  KEY idx_tool_failure_tool(tool_id, created_at),
  KEY idx_tool_failure_agent(agent_id, created_at),
  KEY idx_tool_failure_runtime(runtime_id, created_at),
  KEY idx_tool_failure_session(session_id, created_at),
  KEY idx_tool_failure_trace(trace_id, created_at),
  KEY idx_tool_failure_snapshot(snapshot_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
